#!/bin/bash
set -x
TMPDIR=`mktemp -d`
if [ -d "$TMPDIR" ]; then
    lein run -m honeysql-talk.slides
    cp -r resources/* $TMPDIR/
    git checkout gh-pages
    cp -r $TMPDIR/* .
    git add -A
    git commit -m "new static build"
    git push -u origin gh-pages
    git checkout master
    rm -rf "$TMPDIR"
fi

